sudo: false

language: node_js

node_js:
  - "4.0"
  - "6.0"
  - "8.0"

before_script:
  - npm install -g gulp

after_success:
  - npm run coverage

cache:
  yarn: true
  directories:
    - node_modules
