name: $(BuildID)

resources:
  repositories:
    - repository: apt
      type: github
      name: futagoza/apt
      endpoint: futagoza

variables:
- group: 'env-variables'

jobs:

- template: eslint.yml@apt

- template: node-test.yml@apt
  parameters:
    after:
    - script: yarn coverage
      displayName: 'Publish code coverage results (coveralls.io)'
      env:
        COVERALLS_SERVICE_NAME: $(COVERALLS_SERVICE_NAME)
        COVERALLS_REPO_TOKEN: $(COVERALLS_REPO_TOKEN)
        GIT_BRANCH: $(Build.SourceBranch)
        GIT_COMMIT_SHA: $(Build.SourceVersion)
    publish_test_results_to_pipelines: True
    publish_code_coverage_to_pipelines: True
